remote_theme: pmarsceill/just-the-docs

enable_copy_code_button: true
last_edit_timestamp: true
gh_edit_link: true
gh_edit_repository: "https://github.com/fhict-skilltree/backend-application"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
